---
- name: Update apt cache and upgrade packages
  apt: update_cache=yes upgrade=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - git
    - python-virtualenv
    - python-pip
    - python-setuptools
    - python-dev
    - mongodb
    - python-pycurl
    - libldap2-dev
    - libsasl2-dev
    - libssl-dev