---
- name: Update apt cache and upgrade packages
  apt: update_cache=yes upgrade=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - git

- name: Install foreman
  gem: name=foreman state=latest
