language: python

python:
    - '2.7'

install:
    - "pip install -r requirements-tests.txt"

script:
    - nosetests -xv --cov wristband --cov-config .coveragerc

after_success:
    - coveralls -c .coveragerc