language: python

python:
    - '2.7'

install:
    - "pip install -r requirements-tests.txt"

script:
    - py.test -v --cov wristband --cov-report term-missing --cov-config .coveragerc

after_success:
    - coveralls -c .coveragerc