language: python
python:
- '2.7'
env:
- RELEASES_APP_URI=http://test.com
services:
- mongodb
before_install:
- pip install codecov
install:
- pip install -r requirements/test.txt
script:
- py.test -v --cov=wristband --cov-report term-missing --cov-report xml --cov-config
  .coveragerc --durations=10
after_success:
- codecov
notifications:
  email: false
  slack:
    secure: MccSH8SWpsS4SsWb20y8pKa7p4LAOPjviwPDb+VmsUEHxX8quIR3dIAji7z2wFkQZWgFRex9zEf4miBlZEKQz80DwNNiSrlawAFM49u6dn5ze7zbga8xPc+s8kLF39cYBZpBrFls8DPkSUmM6wlbwRJS/RtQPXbWsnQ8ETynq5OUSVkWq03KCjsPb+ja3k4aQ8UD2W0g1ZzgYIRutkxyHBvSZvS24DRFJUkhBk0wh81jMVaclvu+1sRjJoAF38f7eWPU8hfHEo1khK7IJ84m0rmQLaT8cGInoZTfya+e08XgKlRbFKaOhq8n/rkIg9DoZnMgbomeLVhUBk6816uHx3MIXBb7tecusd3pBI5SEnv80m9OiX9TWIMuXVL7XPS57hfEGAK8X+Kc9tfGZ31ZA+c1/bjFx4+V0e5/32ZJtxwZtBNadmEnHtVcC569InnNpGClsn3pejJkGVkJfRZCDhiWdWIMvhv8+iGqI9s2OU8//5WOi8/yZcP42o0of0GAx6oMAUmHfC9sTpZUjhf3YeJYRGpH6LX4hVQbdQ98acaBc+j0Vl9wmzzvA3ERqfHkm7R+nzgZ8iZu85llsfP9VEvMaMA99yLBkS2tforkDWpjDcGjc/l+uSTKNO6yNdWRoNWNwnDrzOP4It7yuQysILCPZtlYXRT1JwS6QoTE+Qk=
    on_success: change
    on_failure: always