language: python

python:
    - '2.7'

install:
    - "pip install -r requirements-tests.txt"

script:
    - nosetests -xv --with-coverage --cover-package=wristband

after_success:
    - coveralls -c .coveragerc