---
- name: Add environment variables
  lineinfile:
    dest=/home/vagrant/.bashrc
    line="export {{item.variable}}='{{item.value}}'"
    owner=vagrant
  with_items:
    - {variable: 'AUTH_LDAP_SERVER_URI', value: 'ldaps://localhost'}
    - {variable: 'DEPLOYED_ENV', value: 'local'}
    - {variable: 'AUTH_LDAP_USER_SEARCH', value: 'uid={user},ou=groups,dc=example,dc=com'}
    - {variable: 'AUTH_LDAP_SERVER_URI', value: 'ldaps://localhost'}
    - {variable: 'WEBSTORE_URL', value: 'http://test.com'}
    - {variable: 'KIBANA_URL', value: 'https://kibana-{stage}-{security_zone}.example.com/#/dashboard/file/deployments.json?microservice=wristband'}

- name: Add aliases
  lineinfile:
    dest=/home/vagrant/.bash_aliases
    line="alias {{item.alias}}='{{item.value}}'"
    create=yes
    state=present
    owner=vagrant
  with_items:
    - {alias: 'run_wristband', value: '/home/vagrant/venv/bin/python /vagrant/manage.py runserver_plus 0.0.0.0:8000'}
    - {alias: 'run_docktor', value: '/home/vagrant/venv/bin/python /vagrant/mocks/docktor_mock.py'}

- name: Add ou, group and user to LDAP
  command: /usr/bin/ldapadd -x -w password -D cn=Manager,dc=example,dc=com -f /vagrant/provisioning/roles/configuration/files/{{ item }}.ldif
  with_items:
    - ou
    - user
    - group

- name: Set user mars password
  command: ldappasswd -x -w password -D cn=Manager,dc=example,dc=com -s password cn=mars,ou=users,dc=example,dc=com

